- index.html
- register.html
- scripts/main.js
- styles/mainindex.css
This PR fixes an issue where the dropdown options in the **"Select your role"** menu on the register page were not visible until hovered over.  
The problem was caused by styling that made the text and/or background blend into the dropdown container, making the options appear invisible by default.
- Updated dropdown option styles to ensure clear visibility in both default and hover states.
- Adjusted background and text color contrast to meet accessibility standards.
- Improves user experience by making role selection options clearly visible without requiring hover.
- Enhances accessibility for all users, including those with visual impairments.
> Visibility of "Select your role" Dropdown Options on Register Page

- register.html
- styles/auth.css
> select your role option is removed and placed as a placeholder 

- index.html
- manifest.json
- scripts/firebase.js
- scripts/login.html
- scripts/main.js
- service-worker.js
Description
Added a branded logo loader to the home page for a modern look.
Created manifest.json for PWA installability and app icons.
Implemented service-worker.js for offline access and caching.
Registered the service worker on the home page.
Why it matters
These updates improve branding, user experience, and make the app installable with offline support for better reliability.
> Add logo loader, manifest, service worker for PWA

- CODE_OF_CONDUCT.md
This PR upgrades the Code of Conduct to be more engaging, scannable, and contributor-friendly by adding visual and interactive elements.
✅ Changes Made
🪧 Added badges at the top for a welcoming look.
🎉 Introduced GIFs to make key sections fun and memorable (Community, Pledge, Respect, Teamwork).
😎 Incorporated emojis to highlight important points, warnings, and tips.
📝 Improved formatting, spacing, and visual hierarchy for better readability.
🌟 Added a Contributor Wall that dynamically displays contributors’ profiles and badges.
🎯 Why This Matters
Makes the Code of Conduct less intimidating and more approachable.
Encourages contributors to actually read, understand, and follow it.
Builds community culture by recognizing contributors visually.
> Enhanced Code of Conduct with Badges, Emojis, GIFs, and Contributor Wall ✨

- about.html
- index.html
Rationale for this change
Improves navigation and consistency by updating the footer and About Us link as discussed in issue #11.
What changes are included in this PR?
Updated [index.html] footer for premium look and correct navigation links.
Added/updated [about.html] with matching premium footer and consistent design.
Are these changes tested?
Manual browser testing for navigation and footer appearance.
Are there any user-facing changes?
Yes, users will see a consistent footer and working About Us navigation on both pages.
> ISSUE 11 PR about us page 

- features.html
- pricing.html
> Add features.html page and link it with index

- contact.html
updated the contact page & added features page
> Update contact page

- .github/workflows/issue-create-automate-message.yml
- Closes #71
This PR fixes the error in the auto-comment GitHub Action workflow.  
The previous configuration was failing because of an undefined variable and unnecessary duplicate comment logic.
- Updated `.github/workflows/auto-comment.yml`
- Removed the unused variable
- Ensured the action posts only a single comment when a new issue is opened
Yes, the workflow syntax has been validated and the action is expected to run successfully on new issues.
No user-facing changes. This only affects repository automation.
> Fix: Auto-comment workflow on new issues

- security.html
> feat(security): add header with navigation to security page

- cookies.html
- how-to-pitch-your-startup.html
- index.html
- security.html
> refactor(index.html): remove redundant nav-links div

- about.html
- guides.html
- pricing.html
This PR fixes issue #84 by updating the footer on the pricing page to ensure a consistent look and feel across the application.
> Fix: update footer on pricing page for consistency

- api.html
- getting-started-guide.html
- guides.html
- investor-guide.html
- investor-trends-in-2025.html
- messaging-guide.html
- posting-guide.html
- top-5-mistakes-founders-make.html
- Add new navbar styles including hover effects and spacing
- Include terms of service link in navigation
- Adjust logo margin for better alignment
It fixes #102
> style(api): improve navbar styling and add terms link

- api.html
- blog.html
- contact.html
- getting-started-guide.html
- guides.html
- investor-guide.html
- investor-trends-in-2025.html
- messaging-guide.html
- posting-guide.html
- top-5-mistakes-founders-make.html
Add hyperlinks for contact-details links to match dark theme and remove underline by default, adding hover effect
It fixes #99
> style(contact): Hyperlinks for Email and Phone in Contact Page

- api.html
- blog.html
- contact.html
- getting-started-guide.html
- guides.html
- investor-guide.html
- investor-trends-in-2025.html
- messaging-guide.html
- posting-guide.html
- top-5-mistakes-founders-make.html
- Replace complex footer structure with simplified version using inline styles
- Align footer design with index.html's dark theme
It fixes #97
> refactor(blog): simplify footer markup and styling

- api.html
- blog.html
- contact.html
- getting-started-guide.html
- guides.html
- investor-guide.html
- investor-trends-in-2025.html
- messaging-guide.html
- posting-guide.html
- top-5-mistakes-founders-make.html
Maded Footer consitent in contact.html page as per other pages
It fixes #100
> Footer consitent in contact.html page as per other pages

- about.html
- blog.html
- contact.html
- features.html
- guides.html
- help.html
- pricing.html
- styles/navbar.css
- terms.html
Fix issue #118 
> Moved all navigation bar related CSS from individual HTML files into a new shared stylesheet, styles/navbar.css. Updated all relevant HTML files to import the new stylesheet, reducing code duplication and improving maintainability.
- ✅ Centralized navbar styling → easier to update and maintain.
- ✅ Reduced code duplication.
- ✅ Improved responsiveness (works across different screen sizes).
- ✅ Estimated productivity/efficiency improvement of ~60%.
<hr>
> Refactor navbar styles by creating separate CSS file

- README.md
- about.html
- api.html
- blog.html
- contact.html
- cookies.html
- create-proposal.html
- features.html
- guides.html
- help.html
- how-to-pitch-your-startup.html
- index.html
- login.html
- pricing.html
- privacy.html
- proposals.html
- register.html
- scripts/auth.js
- scripts/firebase.js
- scripts/forgot-password.js
- scripts/login.js
- scripts/profile.js
- security.html
- terms.html
This PR addresses the JavaScript improvements identified in issue #120.
**File:** `login.html`
- Changed Google Sign-In button from `type="submit"` to `type="button"`
- Prevents form submission conflicts between regular login and Google Sign-In
**File:** `scripts/profile.js`
- Added comprehensive notification system for user feedback
- Implemented loading states during profile updates (button text changes to "Saving...")
- Added user-friendly success messages: "Profile updated successfully!"
- Added clear error messages: "Failed to update profile. Please try again."
- Proper try-catch-finally error handling
- Button properly disabled during save operation
**File:** `scripts/profile.js` (lines 104-117)
- Added clarifying comment: `// userType values: 'business' for entrepreneurs, …
> Improve JavaScript error handling and add code documentation

- .github/workflows/deploy.yml
Integrated CI/CD pipeline for continuous integration and continuous deployment.
> Added cicd pipeline

- features.html
This PR fixes broken/missing footer links in the features.html file.
Changes Made:
1. Updated footer links to point to the correct pages.
2. Ensured consistency with other pages (like index.html).
3. Cleaned up unused/broken references.
Screenshots :
Before:
After : 
Notes:
1. Synced with upstream main before changes.
2. Verified that the footer on features.html is now aligned and consistent with the rest of the site.
> Fix: Updated footer links in features.html to avoid broken/missing pages

- login.html
- package-lock.json
- package.json
- profile.html
- scripts/firebase.js
- scripts/login.js
- scripts/profile.js
- scripts/register.js
- server.js
- styles/auth.css
- styles/profile.css
- Closes #148
Currently, the logout action executes immediately without confirmation, which can lead to accidental logouts and interrupt the user workflow. This change introduces a confirmation modal to ensure that critical actions like logging out are deliberate, enhancing the overall user experience.
- Added a logout confirmation modal to `profile.html` with:
- Message: “Are you sure you want to log out?”
- Confirm button → Proceeds with logout
- Cancel button → Closes the modal without logging out
- Updated `scripts/profile.js` to handle modal open/close and logout logic
- Added styles for the modal in `profile.css` to match the glass-card aesthetic
- Yes, manually tested in the browser:
- Clicking logout opens the confirmation modal
- Confirm button successfully logs out the user
- …
> Add logout confirmation modal with glass style

- features.html
- index.html
- scripts/main.js
- styles/mainindex.css
- Closes #139 
Currently, the "Go to Top" button uses a simple arrow icon. While functional, it does not align with Venturalink's theme of empowerment and growth. By replacing the arrow with a rocket icon, we create a stronger visual connection to the idea of "launching" or "taking off," which resonates with the platform's entrepreneurial focus. This small UI enhancement makes the experience more engaging and thematic for users.
- Replaced the "Go to Top" arrow icon with a rocket icon.
- Added hover animation: the rocket slightly lifts or scales up on hover.
- Maintained existing smooth scroll-to-top functionality.
- Flame and smoke effects are animated to enhance visual appeal while keeping the button lightweight and performance-friendly.
- Tested manually in multiple browsers to ensure …
> Enhance ‘Go to Top’ Button with Themed Rocket Animation

- .gitignore
- login.html
- register.html
- scripts/register.js
- Closes #170 
The addition of a step-by-step progress bar on the registration page improves the user experience by providing clear, visual feedback on their signup progress. This makes the form feel more interactive and less daunting, potentially increasing form completion rates.v
Added HTML structure for the 5-step progress bar in register.html.
Added CSS to register.html to style the progress bar, circles, and annotations to match the site's theme.
Added JavaScript logic to scripts/register.js to dynamically update the progress bar's state as the user fills in the form fields.
Yes, these changes were tested locally. I confirmed that the progress bar fills correctly as each field (Name, Email, Password, Role, Terms) is completed in the correct order. I also tested the full user flow by …
> [Feature] - Added a Dynamic glowing progress bar for signup page

- cookies.html
> Fixed light theme support for cookie policy page
